### ISSUE TITLE
Printing of com file names when initializing

### ISSUE THREAD

**Issue by swheele2** [QChASM/Aaron#25]
When initilizing, AARON sometimes prints the name of .com files to the screen. We need to clean up all of the printing of AARON.  My guess is that this was added for debugging but just never removed. 

[swheele2@ada4 Example2]$ Aaron example2.in
Checking for required Perl modules...
Necessary Perl modules found. Starting AARON...
Preparing to run transition state searches...
Aaron job started on Fri Aug 10 12:36:59 2018

  Preparing data structures for Cat1/R/ts2...
  Preparing data structures for Cat1/S/ts1...
  Preparing data structures for Cat1/S/ts2...
  Preparing data structures for Cat1/S/ts3...
Cat1/R/ts2/Cat1.R.ts2.1.com
Cat1/S/ts3/Cat1.S.ts3.1.com
Cat1/S/ts1/Cat1.S.ts1.1.com
Cat1/S/ts2/Cat1.S.ts2.1.com
  Preparing data structures for Cat2/R/ts2...

**Comment by yanfeiguan** [comment]
Correct, I forgot to delete some printed message for debug. It has been fixed.
