### ISSUE TITLE
Repeated status printing

### ISSUE THREAD

**Issue by swheele2** [QChASM/Aaron#26]
When there are 2 or more ligands, AARON prints the status of the first ligand twice:

================================================================================
Status for all jobs...(Fri Aug 10 12:38:01 2018)
--------------------------------------------------------------------------------
Status for Cat1 jobs......

Pending jobs:
 Cat1/R/ts2 step 1 attempt 1: No msg recorded
 Cat1/S/ts1 step 1 attempt 1: No msg recorded
 Cat1/S/ts2 step 1 attempt 1: No msg recorded
 Cat1/S/ts3 step 1 attempt 1: No msg recorded

================================================================================
Status for all jobs...(Fri Aug 10 12:38:01 2018)
--------------------------------------------------------------------------------
Status for Cat1 jobs......

Pending jobs:
 Cat1/R/ts2 step 1 attempt 1: No msg recorded
 Cat1/S/ts1 step 1 attempt 1: No msg recorded
 Cat1/S/ts2 step 1 attempt 1: No msg recorded
 Cat1/S/ts3 step 1 attempt 1: No msg recorded
--------------------------------------------------------------------------------
Status for Cat2 jobs......

Pending jobs:
 Cat2/R/ts2 step 1 attempt 1: No msg recorded
 Cat2/S/ts1 step 1 attempt 1: No msg recorded
 Cat2/S/ts2 step 1 attempt 1: No msg recorded
 Cat2/S/ts3 step 1 attempt 1: No msg recorded

**Comment by yanfeiguan** [comment]
Fixed!
