### ISSUE TITLE
com files written to wrong directory

### ISSUE THREAD

**Issue by swheele2** [QChASM/Aaron#29]
In some cases, AARON will write a .com file the main catalyst/ligand directory.  In these cases, AARON essentially stalls for that geometry.

For example, look in /home/swheele2/Aaron_bugs/Cat2:

[swheele2@ada4 Cat2]$ pwd
/home/swheele2/Aaron_bugs/Cat2
[swheele2@ada4 Cat2]$ ls
total 0
drwxr-s---+ 4 swheele2 wheeler 4.0K Aug  5 15:32 Cat2
-rw-r-----  1 swheele2 wheeler 3.1K Aug  6 04:06 Cat2.R.ts2.Cf2.2.com
drwxr-s---+ 4 swheele2 wheeler 4.0K Aug  6 00:15 Cat2_XYZ

[swheele2@ada4 Cf2]$ pwd
/home/swheele2/Aaron_bugs/Cat2/Cat2/R/ts2/Cf2
[swheele2@ada4 Cf2]$ ls
total 128K
-rw-r----- 1 swheele2 wheeler  547 Aug  6 04:06 Cat2.R.ts2.Cf2.2.job
-rw-r----- 1 swheele2 wheeler 1.9K Aug  6 04:38 Cat2.R.ts2.Cf2.2.job.7679661
-rw-r----- 1 swheele2 wheeler 7.3K Aug  6 06:03 Cat2.R.ts2.Cf2.2.job.7679750

We had one case where there were 3 or 4 com files located in that main directory rather than the appropriate subdirectory (unfortunately I didn't take a snapshot of that one).

**Comment by swheele2** [comment]
This seems to always be for Step2, so I think there must be a bug in revert to step 2.  I've had quite a few other Aaron jobs do this.

I removed the .chk files, but everything else is in this .tar.gz file in case you still can't get to Ada:

https://www.dropbox.com/s/nv02mrnsf3uq5jt/Aaron_bug3.tar.gz?dl=0

**Comment by vingman** [comment]
I think I found the bug. Running the stuff in the tar file attached above, and we’ll see if that fixed it.

**Comment by vingman** [comment]
Fixed in commit 3a7b1059a983cfec81baea3c1d82f2cbec4b64d4
